### ISSUE TITLE
Download of 0.5 binary?

### ISSUE THREAD

**Issue by RSully** [aburgh/Disk-Arbitrator#13]

**Comment by kainjow** [comment]
You can find links to compiled executables on the [Downloads](https://github.com/aburgh/Disk-Arbitrator/wiki/Downloads) wiki page.

**Comment by RSully** [comment]
Oh ok, I was looking on the [releases](https://github.com/aburgh/Disk-Arbitrator/releases) page. Might be worth looking into how that GitHub feature works, really quite nice!

**Comment by kainjow** [comment]
The main read me links to the downloads wiki page, but I just added a link for the 0.5 version to the releases page. Thanks.

**Comment by RSully** [comment]
Ok, I only bring it up because if you upload the dmg to GitHub's releases it'll be served over HTTPS as opposed to your insecure+offsite download link.

**Comment by kainjow** [comment]
I updated the links to use https.

**Comment by kainjow** [comment]
I uploaded the dmg for 0.5 so it's attached to the release directly, but kept the wiki link pointing to my site just as a backup.

**Comment by aburgh** [comment]
Ironically, I just noticed the Releases feature a couple days ago and was planning to adopt it. When this project was first put on Github, the downloads were hosted by Github. Later, they removed the ability to host files, so I was forced to find an alternative, which has been to host them on Dropbox. I missed the announcement of Releases, which was July, 2013: [Release Your Software](https://github.com/blog/1547-release-your-software). My preference is to use Releases feature and kill the Downloads wiki page. I will upload the older versions to provide the full history in one location.
