### ISSUE TITLE
Incorrect sort order in listed devices

### ISSUE THREAD

**Issue by jordancoleman** [aburgh/Disk-Arbitrator#15]
When there are devices with high disk numbers (disk10, disk11, etc.), volumes are not correctly listed under the devices they belong to. disk10, disk10s1, and disk10s2, for example, appear between disk1 and disk1s1 in the list.

In the attached screenshot, you can see that disk1s1 and disk1s2 appear to be volumes of disk13, instead of disk1.

![screenshot](https://cloud.githubusercontent.com/assets/3268330/17273191/51c0e4c8-5661-11e6-87ea-73ef49bca6ea.png)

**Comment by kainjow** [comment]
I think this should be fixed. Can you test out this version?

https://kainjow.com/downloads/Disk%20Arbitrator-0.7.dmg

**Comment by aburgh** [comment]
FYI, I was able to reproduce the original problem and to verify the fix, but I'm not suggesting closing the issue before Jordan responds.

**Comment by jordancoleman** [comment]
Yes indeed. Seems to be fixed. Thanks for the quick turnaround.

**Comment by kainjow** [comment]
Final 0.7 version released:

https://github.com/aburgh/Disk-Arbitrator/releases/tag/v0.7.0
