### ISSUE TITLE
0.7 release disk image not mountable

### ISSUE THREAD

**Issue by zenspider** [aburgh/Disk-Arbitrator#16]
It's just totally busted? I can't tell.

**Comment by kainjow** [comment]
Working fine for me on 10.12.1. Can you provide more details?

**Comment by aburgh** [comment]
Works for me, too, 10.12.1. You can verify the hash in Terminal:

```
$ md5 -r /Users/aburgh/Downloads/Disk.Arbitrator-0.7.dmg 
324afbf0765d8303e690d63ef76f1b9a /Users/aburgh/Downloads/Disk.Arbitrator-0.7.dmg
```

Do you have a previous version of Disk Arbitrator running and active? When you attach a disk image and DA blocks the mount, the Disk Images framework reports "No mountable filesystems" and then detaches the image completely. It would be great if a better error message was produced, but that's just how the system operates.

**Comment by zenspider** [comment]
I was upgrading from the previous version. I think it hiccuped on Sierra and left the diskarb cock block in place even tho the process wasn't running anymore. It's been fine since. I'll close.
