### ISSUE TITLE
No longer working with MacOS 13.2 (Intel) 

### ISSUE THREAD

**Issue by GitFun4All** [aburgh/Disk-Arbitrator#46]
Program launches  but unable to install helper: error "The folder “us.burghardt.Disk-Arbitrator.plist” doesn’t exist." when trying. Also Disk window is empty.
;-(

**Comment by DanilKorotenko** [comment]
I will fix it as soon as possible.

**Comment by DanilKorotenko** [comment]
Please, check my fork of this project:
https://github.com/DanilKorotenko/Disk-Arbitrator

**Comment by DanilKorotenko** [comment]
I have updated the build. It works for me.
If it doesn't work on your side, let's discuss and write steps to reproduce, please.

https://github.com/DanilKorotenko/Disk-Arbitrator/releases/tag/v0.8.0

**Comment by GitFun4All** [comment]
Hi - thank you for looking into this so quickly & sorry that I wasted your time.... ;-(
I was running the app from the disk image rather than in the applications directory *bows head in shame*.....
