### ISSUE TITLE
Path?? in Mount - provide instructions, maybe default

### ISSUE THREAD

**Issue by sweerek** [aburgh/Disk-Arbitrator#5]
Newbie problem.

I installed DA 0.4.0.  Its running green and I see the Disks Window.  I plug in a USB stick.  I see its there but not mounted.  I press Mount, pick options and...... type what in the Path?

Can you provide instructions what should go here.... or even better, autofill a default entry for us non-professionals whom simply want a bit more control over what connects to their Mac.

Thanks,

Kevin

**Comment by kainjow** [comment]
A tooltip was added in 9667487f99184511aa7cee08b8b7c92309e4e79b
