### ISSUE TITLE
Problem with Leopard

### ISSUE THREAD

**Issue by davidmorr** [aburgh/Disk-Arbitrator#7]
I tried the latest version (0.4.2) with Leopard (10.5.8). It seemed to open, but nothing ever appeared in the menu bar and disks would still mount.

Version 0.4.1 does still work.

Very useful utility. Has been quite handy recovering a damaged USB flash drive. Thanks.

**Comment by kainjow** [comment]
Looks like this might be fixable by doing what Sparkle did:
https://github.com/sparkle-project/Sparkle/commit/d138f64bd6b6a6cc7c20ae7ba683ab81a49e6bd6

**Comment by kainjow** [comment]
I tested briefly on 10.5 but the only system I have access to is 32-bit. However, I just released an 0.5 version, and for that I disabled the 64-bit version from running on 10.5, so this issue should be resolved.
